/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

/**
 *
 * @author zaqwe
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        SearchBar.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        MmBtn = new javax.swing.JLabel();
        MBtn = new javax.swing.JLabel();
        PBtn = new javax.swing.JLabel();
        PlBtn = new javax.swing.JLabel();
        AddIcon = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        SearchIcon = new javax.swing.JLabel();
        SearBarBG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Logo.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        MmBtn.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        MmBtn.setForeground(new java.awt.Color(255, 255, 255));
        MmBtn.setText("หน้าหลัก");
        getContentPane().add(MmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        MBtn.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        MBtn.setForeground(new java.awt.Color(153, 153, 153));
        MBtn.setText("เพลง");
        MBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MBtnMouseClicked(evt);
            }
        });
        getContentPane().add(MBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        PBtn.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        PBtn.setForeground(new java.awt.Color(153, 153, 153));
        PBtn.setText("พอดแคสต์");
        PBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PBtnMouseClicked(evt);
            }
        });
        getContentPane().add(PBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        PlBtn.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        PlBtn.setForeground(new java.awt.Color(153, 153, 153));
        PlBtn.setText("เพลย์ลิสต์");
        PlBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlBtnMouseClicked(evt);
            }
        });
        getContentPane().add(PlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        AddIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Add Square 5.png"))); // NOI18N
        AddIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddIconMouseClicked(evt);
            }
        });
        getContentPane().add(AddIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, -1, -1));

        SearchBar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SearchBar.setForeground(new java.awt.Color(153, 153, 153));
        SearchBar.setBorder(null);
        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 1110, 50));

        SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Search Normal.png"))); // NOI18N
        getContentPane().add(SearchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 110, 40, -1));

        SearBarBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/MainMenuSearchBar.png"))); // NOI18N
        getContentPane().add(SearBarBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/MainMenuBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/gradient (2).png"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(1280, 832));
        Background.setMinimumSize(new java.awt.Dimension(1280, 832));
        Background.setPreferredSize(new java.awt.Dimension(1280, 832));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void MBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MBtnMouseClicked
    this.dispose();
    
    // เปิดหน้าจอ MusicLibrary
    MusicLibrary musicLibrary = new MusicLibrary();
    musicLibrary.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
    musicLibrary.setVisible(true);
    }//GEN-LAST:event_MBtnMouseClicked

    private void PBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PBtnMouseClicked
    this.dispose();
    
    // เปิดหน้าจอ PodcastLibray
    PodcastLibrary podcastLibrary = new PodcastLibrary();
    podcastLibrary.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
    podcastLibrary.setVisible(true);
    }//GEN-LAST:event_PBtnMouseClicked

    private void PlBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlBtnMouseClicked
    this.dispose();
    
    // เปิดหน้าจอ PlaylistLibrary
    PlaylistLibrary playlisttLibrary = new PlaylistLibrary();
    playlisttLibrary.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
    playlisttLibrary.setVisible(true);       
    }//GEN-LAST:event_PlBtnMouseClicked

    private void AddIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddIconMouseClicked
    this.dispose();
    
    // เปิดหน้าจอ Upload
    Upload upload = new Upload();
    upload.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
    upload  .setVisible(true);   
    }//GEN-LAST:event_AddIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddIcon;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel MBtn;
    private javax.swing.JLabel MmBtn;
    private javax.swing.JLabel PBtn;
    private javax.swing.JLabel PlBtn;
    private javax.swing.JLabel SearBarBG;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JLabel SearchIcon;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
