/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import com.mpatric.mp3agic.InvalidDataException;
import com.mpatric.mp3agic.NotSupportedException;
import com.mpatric.mp3agic.UnsupportedTagException;
import java.io.File;
import java.io.IOException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author zaqwe
 */
public class MusicUpload extends javax.swing.JFrame {  
    private MediaControl player;
    private Music music;
    private final String userHome = System.getProperty("user.home");
    private final String musicFolderPath = userHome + "\\Documents\\NetBeansProjects\\JavaApplication1\\music";
    
public MusicUpload() {
        initComponents();
        player = new MediaControl("C:\\Users\\zaqwe\\Documents\\NetBeansProjects\\JavaApplication1\\music");
         MusicTileTF.setBackground(new java.awt.Color(0,0,0,1));
         MusicArtistTF.setBackground(new java.awt.Color(0,0,0,1));
         MusicAlbumTF.setBackground(new java.awt.Color(0,0,0,1));
         GenreCB.setBackground(new java.awt.Color(0,0,0,1));
         createMusicFolderIfNotExists();
    }
    private void createMusicFolderIfNotExists() {
        File folder = new File(musicFolderPath);
        if (!folder.exists()) {
            folder.mkdirs(); // สร้างโฟลเดอร์หากยังไม่มี
            System.out.println("Music folder created at: " + musicFolderPath);
        }
    }

    private void initMusic(String filePath) throws UnsupportedTagException, InvalidDataException, IOException {
        try {
               music = new Music(filePath);
               System.out.println("Music file loaded successfully: " + filePath);
           } catch (UnsupportedTagException | InvalidDataException | IOException e) {
               e.printStackTrace();
               JOptionPane.showMessageDialog(this, "Error loading MP3 file: " + e.getMessage());
               music = null; // Reset music object if failed
           }
    }
// เมื่อกดปุ่ม Save
private void saveMusicMetadata() {
    try {
        // รับค่าจาก TextField
        String title = MusicTileTF.getText().trim();
        String artist = MusicArtistTF.getText().trim();
        String album = MusicAlbumTF.getText().trim();
        String genre = (String) GenreCB.getSelectedItem();

        if (title.isEmpty() || artist.isEmpty() || album.isEmpty() || genre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields before saving.");
            return;
        }

        // ตรวจสอบว่า music ถูกสร้างเรียบร้อยหรือยัง
        if (music != null) {
            // ตั้งค่า Metadata
            music.setMusicTitle(title);
            music.setMusicArtist(artist);
            music.setMusicAlbum(album);
            music.setMusicGenre(genre);

            // กำหนด Path สำหรับบันทึกไฟล์
            String outputFilePath = musicFolderPath + "\\" + title.replaceAll("[^a-zA-Z0-9]", "_") + ".mp3";

            // บันทึกข้อมูลลง MP3
            music.save(outputFilePath);

            JOptionPane.showMessageDialog(this, "Music metadata saved successfully at: " + outputFilePath);
        } else {
            JOptionPane.showMessageDialog(this, "No music file initialized. Please upload an MP3 file first.");
        }
    } catch (IOException | NotSupportedException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error saving music metadata: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackBtn = new javax.swing.JLabel();
        MusicArt = new javax.swing.JLabel();
        PodacastHead = new javax.swing.JLabel();
        MP3Filename = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MusicTileTF = new javax.swing.JTextField();
        MusicAlbumTF = new javax.swing.JTextField();
        MusicArtistTF = new javax.swing.JTextField();
        GenreCB = new javax.swing.JComboBox<>();
        IconSpecLb = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JLabel();
        TextfieldBg1 = new javax.swing.JLabel();
        TextfieldBg2 = new javax.swing.JLabel();
        TextfieldBg3 = new javax.swing.JLabel();
        TextfieldBg4 = new javax.swing.JLabel();
        TextfieldBg5 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Back.png"))); // NOI18N
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        MusicArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/selectUpload.png"))); // NOI18N
        MusicArt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MusicArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusicArtMouseClicked(evt);
            }
        });
        getContentPane().add(MusicArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 280, 240));

        PodacastHead.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        PodacastHead.setForeground(new java.awt.Color(255, 255, 255));
        PodacastHead.setText("อัปโหลดเพลง");
        getContentPane().add(PodacastHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        MP3Filename.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        MP3Filename.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(MP3Filename, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 530, 50));

        jLabel2.setFont(new java.awt.Font("Prompt", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("เลือกไฟล์:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Prompt", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ชื่อเพลง:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, -1, -1));

        jLabel4.setFont(new java.awt.Font("Prompt", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("แนวเพลง:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 720, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uploadIcon.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 50, 50));

        jLabel5.setFont(new java.awt.Font("Prompt", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ชื่อศิลปิน:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, -1, -1));

        jLabel6.setFont(new java.awt.Font("Prompt", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ชื่ออัลบั้ม:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 650, -1, -1));

        MusicTileTF.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        MusicTileTF.setForeground(new java.awt.Color(255, 255, 255));
        MusicTileTF.setBorder(null);
        MusicTileTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicTileTFActionPerformed(evt);
            }
        });
        getContentPane().add(MusicTileTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 560, 50));

        MusicAlbumTF.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        MusicAlbumTF.setForeground(new java.awt.Color(255, 255, 255));
        MusicAlbumTF.setBorder(null);
        MusicAlbumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicAlbumTFActionPerformed(evt);
            }
        });
        getContentPane().add(MusicAlbumTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 560, 50));

        MusicArtistTF.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        MusicArtistTF.setForeground(new java.awt.Color(255, 255, 255));
        MusicArtistTF.setBorder(null);
        MusicArtistTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicArtistTFActionPerformed(evt);
            }
        });
        getContentPane().add(MusicArtistTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 560, 50));

        GenreCB.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        GenreCB.setForeground(new java.awt.Color(255, 255, 255));
        GenreCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Pop", "Hip Hop", "R&B", "Rock", "Dance", "Country", "Jazz", "EDM", "Classical", "Reggae" }));
        GenreCB.setBorder(null);
        GenreCB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(GenreCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, 580, 50));

        IconSpecLb.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        IconSpecLb.setForeground(new java.awt.Color(204, 204, 204));
        IconSpecLb.setText("รองรับไฟล์ประเภท .jpg, .png เท่านั้น ขนาดแนะนำ 300x300");
        getContentPane().add(IconSpecLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/SaveBtn.png"))); // NOI18N
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 800, -1, -1));

        TextfieldBg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/UploadTextfieldBg.png"))); // NOI18N
        getContentPane().add(TextfieldBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 710, 590, -1));

        TextfieldBg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/UploadTextfieldBg.png"))); // NOI18N
        getContentPane().add(TextfieldBg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        TextfieldBg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/UploadTextfieldBg.png"))); // NOI18N
        getContentPane().add(TextfieldBg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, -1, -1));

        TextfieldBg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/UploadTextfieldBg.png"))); // NOI18N
        getContentPane().add(TextfieldBg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        TextfieldBg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/UploadTextfieldBg.png"))); // NOI18N
        getContentPane().add(TextfieldBg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/gradient.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("MP3 Files", "mp3"));
    
    // ถ้าผู้ใช้เลือกไฟล์
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            // โหลดไฟล์ MP3
            try {
                initMusic(selectedFile.getAbsolutePath());  // โหลดไฟล์ MP3 ให้กับ Music
                MP3Filename.setText(selectedFile.getName());  // แสดงชื่อไฟล์ใน UI
            } catch (UnsupportedTagException | InvalidDataException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error loading MP3 file: " + e.getMessage());
            } catch (IOException ex) {
                 Logger.getLogger(MusicUpload.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void MusicTileTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicTileTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicTileTFActionPerformed

    private void MusicAlbumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicAlbumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicAlbumTFActionPerformed

    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked
        saveMusicMetadata();
    }//GEN-LAST:event_SaveBtnMouseClicked

    private void MusicArtistTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicArtistTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicArtistTFActionPerformed

    private void MusicArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicArtMouseClicked
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Select Music Art");  // ตั้งชื่อ dialog
    fileChooser.setFileFilter(new FileNameExtensionFilter("Image files", "jpg", "png"));  // กรองเฉพาะไฟล์ภาพ

    // ถ้าผู้ใช้เลือกไฟล์และคลิก Open
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();  // รับไฟล์ที่ผู้ใช้เลือก

            try {
                // นำไฟล์ที่เลือกมาตั้งค่าให้กับ Music
                music.setMusicAlbumArt(selectedFile.getAbsolutePath());

                // ตั้งค่า icon ของ MusicArt ให้เป็นไฟล์ภาพที่เลือก
                ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
                MusicArt.setIcon(icon);  // เปลี่ยน icon ของ MusicArt
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error setting music art: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_MusicArtMouseClicked

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        this.dispose();

        // เปิดหน้าจอ MainMenu
        MusicLibrary musicLibrary = new MusicLibrary();
        musicLibrary.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
        musicLibrary.setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicUpload().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JComboBox<String> GenreCB;
    private javax.swing.JLabel IconSpecLb;
    private javax.swing.JLabel MP3Filename;
    private javax.swing.JTextField MusicAlbumTF;
    private javax.swing.JLabel MusicArt;
    private javax.swing.JTextField MusicArtistTF;
    private javax.swing.JTextField MusicTileTF;
    private javax.swing.JLabel PodacastHead;
    private javax.swing.JLabel SaveBtn;
    private javax.swing.JLabel TextfieldBg1;
    private javax.swing.JLabel TextfieldBg2;
    private javax.swing.JLabel TextfieldBg3;
    private javax.swing.JLabel TextfieldBg4;
    private javax.swing.JLabel TextfieldBg5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
