/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author zaqwe
 */
public class PlaylistCreate extends javax.swing.JFrame {
        private Playlist playlist;
        private String userHome = System.getProperty("user.home");
        private String PlaylistFolderPath = userHome + "\\Documents\\NetBeansProjects\\JavaApplication1\\Playlist";
        
    public PlaylistCreate() {
        initComponents();
        PlaylistTF.setBackground(new java.awt.Color(0,0,0,1));
    }
    
        private void createPlaylistFolderIfNotExists() {
        File folder = new File(PlaylistFolderPath);
        if (!folder.exists()) {
            folder.mkdirs(); // สร้างโฟลเดอร์หากยังไม่มี
            System.out.println("Podcast folder created at: " + PlaylistFolderPath);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlaylistArt = new javax.swing.JLabel();
        PodacastHead = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PlaylistTF = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JLabel();
        TextfieldBg2 = new javax.swing.JLabel();
        IconSpecLb = new javax.swing.JLabel();
        BackBtn = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlaylistArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/selectUpload.png"))); // NOI18N
        PlaylistArt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PlaylistArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlaylistArtMouseClicked(evt);
            }
        });
        getContentPane().add(PlaylistArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 280, 240));

        PodacastHead.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        PodacastHead.setForeground(new java.awt.Color(255, 255, 255));
        PodacastHead.setText("สร้างเพลย์ลิสต์");
        getContentPane().add(PodacastHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Prompt", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ชื่อ:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        PlaylistTF.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        PlaylistTF.setForeground(new java.awt.Color(255, 255, 255));
        PlaylistTF.setBorder(null);
        PlaylistTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaylistTFActionPerformed(evt);
            }
        });
        getContentPane().add(PlaylistTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 560, 50));

        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/SaveBtn.png"))); // NOI18N
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 690, -1, -1));

        TextfieldBg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/UploadTextfieldBg.png"))); // NOI18N
        getContentPane().add(TextfieldBg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        IconSpecLb.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        IconSpecLb.setForeground(new java.awt.Color(204, 204, 204));
        IconSpecLb.setText("รองรับไฟล์ประเภท .ico เท่านั้น ขนาดแนะนำ 300x300");
        getContentPane().add(IconSpecLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Back.png"))); // NOI18N
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Background.setForeground(new java.awt.Color(204, 204, 204));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/gradient.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlaylistArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlaylistArtMouseClicked

    }//GEN-LAST:event_PlaylistArtMouseClicked

    private void PlaylistTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaylistTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlaylistTFActionPerformed

    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked

    }//GEN-LAST:event_SaveBtnMouseClicked

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
     this.dispose();
    
    // เปิดหน้าจอ MainMenu
    PlaylistLibrary playlistLibrary = new PlaylistLibrary();
    playlistLibrary.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
    playlistLibrary.setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistCreate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel IconSpecLb;
    private javax.swing.JLabel PlaylistArt;
    private javax.swing.JTextField PlaylistTF;
    private javax.swing.JLabel PodacastHead;
    private javax.swing.JLabel SaveBtn;
    private javax.swing.JLabel TextfieldBg2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
