/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import com.mpatric.mp3agic.ID3v2;
import com.mpatric.mp3agic.Mp3File;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zaqwe
 */
public class PodcastLibrary extends javax.swing.JFrame {
       private String userHome = System.getProperty("user.home");
       private String PodcastFolderPath = userHome + "\\Documents\\NetBeansProjects\\JavaApplication1\\Podcast";
    public PodcastLibrary() {
        initComponents();
        ShowPodcast();
        
        // ให้ช่อง Search(JTextField) ล่องหน
        SearchBar.setBackground(new java.awt.Color(0,0,0,1));
        
        // ตั้งค่า ช่องแสดงเพลง
        Tlistpodcast.setForeground(Color.WHITE);
        Tlistpodcast.setRowHeight(60);
        Tlistpodcast.setBackground(new Color(33, 33, 33));
        Tlistpodcast.getTableHeader().setBackground(new Color(33, 33, 33));
        Tlistpodcast.getTableHeader().setFont(new Font("Prompt", Font.PLAIN, 14));
        
        // ตั้งค่า ScrollPane
        jScrollPane1.setBackground(new Color(33, 33, 33));
        jScrollPane1.getViewport().setBackground(new Color(33, 33, 33));
        jScrollPane1.setForeground(new Color(180, 180, 180));
    }
    
private void ShowPodcast() {
    String[] columnNames = {"Cover", "Title", "Artist"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
        @Override
        public Class<?> getColumnClass(int column) {
            return column == 0 ? ImageIcon.class : String.class; // First column is ImageIcon
        }
    };
    File PodcastFolder = new File(PodcastFolderPath);

    if (PodcastFolder.exists() && PodcastFolder.isDirectory()) {
        File[] files = PodcastFolder.listFiles((dir, name) -> name.endsWith(".mp3"));
        if (files != null) {
            for (File file : files) {
                try {
                    Mp3File mp3File = new Mp3File(file);
                    if (mp3File.hasId3v2Tag()) {
                        ID3v2 id3v2Tag = mp3File.getId3v2Tag();
                        String title = id3v2Tag.getTitle() != null ? id3v2Tag.getTitle() : "Unknown";
                        String artist = id3v2Tag.getArtist() != null ? id3v2Tag.getArtist() : "Unknown";

                        ImageIcon albumArt = null;
                        if (id3v2Tag.getAlbumImage() != null) {
                            byte[] imageData = id3v2Tag.getAlbumImage();
                            ByteArrayInputStream bis = new ByteArrayInputStream(imageData);
                            Image image = ImageIO.read(bis);
                            albumArt = new ImageIcon(image.getScaledInstance(50, 50, Image.SCALE_SMOOTH));
                        } else {
                            albumArt = new ImageIcon(new ImageIcon("default_cover.png").getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
                        }

                        model.addRow(new Object[]{albumArt, title, artist});
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Podcast folder not found!", "Error", JOptionPane.ERROR_MESSAGE);
    }

    Tlistpodcast.setModel(model);
    Tlistpodcast.setBackground(new Color(33, 33, 33));
    Tlistpodcast.getTableHeader().setVisible(false);

    // Adjust alignment for text columns
    DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
    leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);
    for (int i = 1; i < Tlistpodcast.getColumnModel().getColumnCount(); i++) {
        Tlistpodcast.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        FilterBackGround = new javax.swing.JLabel();
        PBtn = new javax.swing.JLabel();
        MmBtn = new javax.swing.JLabel();
        PlBtn = new javax.swing.JLabel();
        MBtn = new javax.swing.JLabel();
        AddIcon = new javax.swing.JLabel();
        SearchBar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SecretBG = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tlistpodcast = new javax.swing.JTable();
        SearchIcon = new javax.swing.JLabel();
        SearBarBG = new javax.swing.JLabel();
        MlistBG = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Logo.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        FilterBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/FilterBG.png"))); // NOI18N
        getContentPane().add(FilterBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 700));

        PBtn.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        PBtn.setForeground(new java.awt.Color(255, 255, 255));
        PBtn.setText("พอดแคสต์");
        getContentPane().add(PBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        MmBtn.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        MmBtn.setForeground(new java.awt.Color(153, 153, 153));
        MmBtn.setText("หน้าหลัก");
        MmBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MmBtnMouseClicked(evt);
            }
        });
        getContentPane().add(MmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        PlBtn.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        PlBtn.setForeground(new java.awt.Color(153, 153, 153));
        PlBtn.setText("เพลย์ลิสต์");
        PlBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlBtnMouseClicked(evt);
            }
        });
        getContentPane().add(PlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        MBtn.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        MBtn.setForeground(new java.awt.Color(153, 153, 153));
        MBtn.setText("เพลง");
        MBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MBtnMouseClicked(evt);
            }
        });
        getContentPane().add(MBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        AddIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Add Square 5.png"))); // NOI18N
        AddIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddIconMouseClicked(evt);
            }
        });
        getContentPane().add(AddIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 50, -1, -1));

        SearchBar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SearchBar.setForeground(new java.awt.Color(153, 153, 153));
        SearchBar.setBorder(null);
        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 900, 50));

        jLabel2.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("ชื่อ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("ผู้เล่า");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, -1, -1));

        SecretBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/SecretBG.png"))); // NOI18N
        SecretBG.setText("jLabel2");
        getContentPane().add(SecretBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 950, 30));

        jScrollPane1.setBackground(new java.awt.Color(33, 33, 33));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(33, 33, 33));
        jScrollPane1.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N

        Tlistpodcast.setBackground(new java.awt.Color(33, 33, 33));
        Tlistpodcast.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        Tlistpodcast.setForeground(new java.awt.Color(33, 33, 33));
        Tlistpodcast.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tlistpodcast.setDragEnabled(true);
        Tlistpodcast.setEnabled(false);
        Tlistpodcast.setGridColor(new java.awt.Color(33, 33, 33));
        Tlistpodcast.setSelectionBackground(new java.awt.Color(33, 33, 33));
        Tlistpodcast.setSelectionForeground(new java.awt.Color(33, 33, 33));
        jScrollPane1.setViewportView(Tlistpodcast);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 930, 610));

        SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Search Normal.png"))); // NOI18N
        getContentPane().add(SearchIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, 40, -1));

        SearBarBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/SearchBar.png"))); // NOI18N
        SearBarBG.setText("jLabel6");
        getContentPane().add(SearBarBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        MlistBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/M&PListBG.png"))); // NOI18N
        getContentPane().add(MlistBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, 650));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/gradient (2).png"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(1280, 832));
        Background.setMinimumSize(new java.awt.Dimension(1280, 832));
        Background.setPreferredSize(new java.awt.Dimension(1280, 832));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void MmBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MmBtnMouseClicked
     this.dispose();
    
    // เปิดหน้าจอ MainMenu
    MainMenu mainMeu = new MainMenu();
    mainMeu.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
    mainMeu.setVisible(true);
    }//GEN-LAST:event_MmBtnMouseClicked

    private void MBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MBtnMouseClicked
     this.dispose();
    
    // เปิดหน้าจอ MusicLibrary
    MusicLibrary musicLibrary = new MusicLibrary();
    musicLibrary.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
    musicLibrary.setVisible(true);
    }//GEN-LAST:event_MBtnMouseClicked

    private void PlBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlBtnMouseClicked
    this.dispose();
    
    // เปิดหน้าจอ PlaylistLibrary
    PlaylistLibrary playlisttLibrary = new PlaylistLibrary();
    playlisttLibrary.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
    playlisttLibrary.setVisible(true);       
    }//GEN-LAST:event_PlBtnMouseClicked

    private void AddIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddIconMouseClicked
    this.dispose();
    
    // เปิดหน้าจอ Upload
    Upload upload = new Upload();
    upload.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
    upload  .setVisible(true);   
    }//GEN-LAST:event_AddIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PodcastLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PodcastLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PodcastLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PodcastLibrary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PodcastLibrary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddIcon;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel FilterBackGround;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel MBtn;
    private javax.swing.JLabel MlistBG;
    private javax.swing.JLabel MmBtn;
    private javax.swing.JLabel PBtn;
    private javax.swing.JLabel PlBtn;
    private javax.swing.JLabel SearBarBG;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JLabel SearchIcon;
    private javax.swing.JLabel SecretBG;
    private javax.swing.JTable Tlistpodcast;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
