/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import com.mpatric.mp3agic.InvalidDataException;
import com.mpatric.mp3agic.NotSupportedException;
import com.mpatric.mp3agic.UnsupportedTagException;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author zaqwe
 */
public class PodcastUpload extends javax.swing.JFrame {
    private MediaControl player;
    private Podcast podcast;
    private final String userHome = System.getProperty("user.home");
    private final String PodcastFolderPath = userHome + "\\Documents\\NetBeansProjects\\JavaApplication1\\Podcast";
    /**
     * Creates new form PodcastUpload
     */
    public PodcastUpload() {
        initComponents();
        player = new MediaControl("C:\\Users\\zaqwe\\Documents\\NetBeansProjects\\JavaApplication1\\Podcast");
         StoryTeller.setBackground(new java.awt.Color(0,0,0,1));
         PodcastTitleTF1.setBackground(new java.awt.Color(0,0,0,1));
         createPodcastFolderIfNotExists();
    }
    private void createPodcastFolderIfNotExists() {
        File folder = new File(PodcastFolderPath);
        if (!folder.exists()) {
            folder.mkdirs(); // สร้างโฟลเดอร์หากยังไม่มี
            System.out.println("Podcast folder created at: " + PodcastFolderPath);
        }
    }

    private void initPodcast(String filePath) throws UnsupportedTagException, InvalidDataException {
        try {
            podcast = new Podcast(filePath);
        } catch (IOException | UnsupportedTagException | InvalidDataException e) {
            e.printStackTrace();
        }
    }
// เมื่อกดปุ่ม Save
private void savePodcastMetadata() {
    try {
        // รับค่าจาก TextField
        String title = PodcastTitleTF1.getText();
        String storyteller = StoryTeller.getText();

        // ตรวจสอบว่า podcast ถูกสร้างเรียบร้อยหรือยัง
        if (podcast != null) {
            // ตั้งค่า Metadata
            podcast.setPodcastTitle(title);       // ตั้งค่าหัวข้อของ Podcast
            podcast.setStoryteller(storyteller);  // ตั้งค่าผู้เล่า

            // กำหนด Path สำหรับบันทึกไฟล์
            String outputFilePath = PodcastFolderPath + "\\" + title.replaceAll("[^a-zA-Z0-9]", "_") + ".mp3";

            // บันทึกข้อมูลลง MP3
            podcast.save(outputFilePath);

        } else {
            System.out.println("No podcast file initialized!");
        }
    } catch (IOException | NotSupportedException e) {
        e.printStackTrace();
    }
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackBtn = new javax.swing.JLabel();
        PodcastArt = new javax.swing.JLabel();
        PodacastHead = new javax.swing.JLabel();
        MP3Filename = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ChooseMp3 = new javax.swing.JLabel();
        StoryTeller = new javax.swing.JTextField();
        PodcastTitleTF1 = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JLabel();
        TextfieldBg1 = new javax.swing.JLabel();
        TextfieldBg2 = new javax.swing.JLabel();
        TextfieldBg3 = new javax.swing.JLabel();
        IconSpecLb = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Back.png"))); // NOI18N
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        PodcastArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/selectUpload.png"))); // NOI18N
        PodcastArt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PodcastArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PodcastArtMouseClicked(evt);
            }
        });
        getContentPane().add(PodcastArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 280, 240));

        PodacastHead.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        PodacastHead.setForeground(new java.awt.Color(255, 255, 255));
        PodacastHead.setText("อัปโหลดพอดแคสต์");
        getContentPane().add(PodacastHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        MP3Filename.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        MP3Filename.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(MP3Filename, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 530, 50));

        jLabel2.setFont(new java.awt.Font("Prompt", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("เลือกไฟล์:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Prompt", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ชื่อพอดแคสต์:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, -1));

        jLabel4.setFont(new java.awt.Font("Prompt", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ผู้เล่า:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, -1));

        ChooseMp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uploadIcon.png"))); // NOI18N
        ChooseMp3.setText("jLabel1");
        ChooseMp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChooseMp3MouseClicked(evt);
            }
        });
        getContentPane().add(ChooseMp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 50, 50));

        StoryTeller.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        StoryTeller.setForeground(new java.awt.Color(255, 255, 255));
        StoryTeller.setBorder(null);
        StoryTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoryTellerActionPerformed(evt);
            }
        });
        getContentPane().add(StoryTeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 560, 50));

        PodcastTitleTF1.setFont(new java.awt.Font("Prompt", 0, 18)); // NOI18N
        PodcastTitleTF1.setForeground(new java.awt.Color(255, 255, 255));
        PodcastTitleTF1.setBorder(null);
        PodcastTitleTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PodcastTitleTF1ActionPerformed(evt);
            }
        });
        getContentPane().add(PodcastTitleTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 512, 560, 50));

        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/SaveBtn.png"))); // NOI18N
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 690, -1, -1));

        TextfieldBg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/UploadTextfieldBg.png"))); // NOI18N
        getContentPane().add(TextfieldBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        TextfieldBg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/UploadTextfieldBg.png"))); // NOI18N
        getContentPane().add(TextfieldBg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        TextfieldBg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/UploadTextfieldBg.png"))); // NOI18N
        getContentPane().add(TextfieldBg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, -1, -1));

        IconSpecLb.setFont(new java.awt.Font("Prompt", 0, 12)); // NOI18N
        IconSpecLb.setForeground(new java.awt.Color(204, 204, 204));
        IconSpecLb.setText("รองรับไฟล์ประเภท .jpg, .png เท่านั้น ขนาดแนะนำ 300x300");
        getContentPane().add(IconSpecLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        Background.setForeground(new java.awt.Color(204, 204, 204));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/gradient.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StoryTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoryTellerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StoryTellerActionPerformed

    private void PodcastTitleTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PodcastTitleTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PodcastTitleTF1ActionPerformed

    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked
            try {
            // รับค่าจาก TextField
            String title = PodcastTitleTF1.getText();
            String storyteller = StoryTeller.getText();

            // ตรวจสอบว่า podcast ถูกสร้างเรียบร้อยหรือยัง
            if (podcast != null) {
                // ตั้งค่า Metadata
                podcast.setPodcastTitle(title);       // ตั้งค่าหัวข้อของ Podcast
                podcast.setStoryteller(storyteller);  // ตั้งค่าผู้เล่า

                // กำหนด Path สำหรับบันทึกไฟล์ (ใช้ชื่อที่ผู้ใช้กรอกใน Title)
                String outputFilePath = PodcastFolderPath + "\\" + title.replaceAll("[^a-zA-Z0-9]", "_") + ".mp3";

                // บันทึกข้อมูลลง MP3
                podcast.save(outputFilePath);
            } else {
                JOptionPane.showMessageDialog(this, "No podcast file initialized!");
            }
        } catch (IOException | NotSupportedException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving podcast metadata: " + e.getMessage());
        }
    }//GEN-LAST:event_SaveBtnMouseClicked

    private void ChooseMp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseMp3MouseClicked
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter("MP3 Files", "mp3"));

        // ถ้าผู้ใช้เลือกไฟล์
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            // โหลดไฟล์ MP3
            try {
                initPodcast(selectedFile.getAbsolutePath());  // โหลดไฟล์ MP3 ให้กับ podcast
                MP3Filename.setText(selectedFile.getName());  // แสดงชื่อไฟล์ใน UI
            } catch (UnsupportedTagException | InvalidDataException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error loading MP3 file: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_ChooseMp3MouseClicked

    private void PodcastArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PodcastArtMouseClicked
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Select Podcast Art");  // ตั้งชื่อ dialog
    fileChooser.setFileFilter(new FileNameExtensionFilter("Image files", "jpg", "png"));  // กรองเฉพาะไฟล์ภาพ

    // ถ้าผู้ใช้เลือกไฟล์และคลิก Open
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();  // รับไฟล์ที่ผู้ใช้เลือก

            try {
                // นำไฟล์ที่เลือกมาตั้งค่าให้กับ Podcast
                podcast.setPodcastArt(selectedFile.getAbsolutePath());

                // ตั้งค่า icon ของ PodcastArt ให้เป็นไฟล์ภาพที่เลือก
                ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
                PodcastArt.setIcon(icon);  // เปลี่ยน icon ของ PodcastArt
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error setting podcast art: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_PodcastArtMouseClicked

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        this.dispose();

        // เปิดหน้าจอ MainMenu
        PodcastLibrary podcastLibrary = new PodcastLibrary();
        podcastLibrary.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
        podcastLibrary.setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PodcastUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PodcastUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PodcastUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PodcastUpload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PodcastUpload().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel ChooseMp3;
    private javax.swing.JLabel IconSpecLb;
    private javax.swing.JLabel MP3Filename;
    private javax.swing.JLabel PodacastHead;
    private javax.swing.JLabel PodcastArt;
    private javax.swing.JTextField PodcastTitleTF1;
    private javax.swing.JLabel SaveBtn;
    private javax.swing.JTextField StoryTeller;
    private javax.swing.JLabel TextfieldBg1;
    private javax.swing.JLabel TextfieldBg2;
    private javax.swing.JLabel TextfieldBg3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
