/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author zaqwe
 */
public class PodcastMenu extends javax.swing.JFrame {
    private MediaControl player;
    private boolean isPlaying = false;
    private boolean isShuffle = false;
    private javax.swing.Timer timer;
    private final String userHome = System.getProperty("user.home");
    private final String podcastFolderPath = userHome + "\\Documents\\NetBeansProjects\\JavaApplication1\\Podcast";
    private Podcast podcast;
 
    public PodcastMenu() {
        initComponents();  // NetBeans will handle the GUI component setup
        setLocationRelativeTo(null);
        //player = new MediaControl("C:\\Users\\zaqwe\\Documents\\NetBeansProjects\\JavaApplication1\\music");
        player = new MediaControl(podcastFolderPath);
        PodcastTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PodcastArtist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlayerStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mp3Art.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    }
 public void updatePodcastInfo() {
        if (player.getCurrentPodcast() != null) {
            PodcastTitle.setText(player.getCurrentPodcast().getPodcastTitle());
            PodcastArtist.setText(player.getCurrentPodcast().getStoryteller());
            PlayerStatus.setText("กำลังเล่น");
        } else {
            PlayerStatus.setText("ไม่มีเพลงเล่นอยู่ในตอนนี้");
        }
    }
    
    public void updatePodcastArt(){
        byte[] albumArt = player.getCurrentPodcast().getPodcastArt();
            if (albumArt != null) {
                // Convert byte array to ImageIcon
                ImageIcon originalIcon = new ImageIcon(albumArt);

                // Resize the image to fit the label's size (100x100)
                Image img = originalIcon.getImage();  // Get the Image from the Icon
                Image scaledImg = img.getScaledInstance(300, 300, Image.SCALE_SMOOTH);  // Scale the image
                ImageIcon scaledIcon = new ImageIcon(scaledImg);  // Create a new ImageIcon with the scaled image

                // Set the resized ImageIcon to the JLabel
                Mp3Art.setIcon(scaledIcon);
                } else {
                    // Optionally, set a default icon or message if there's no album art
                    Mp3Art.setIcon(new ImageIcon("/Photo/NoMusicArt.png"));
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mp3Art = new javax.swing.JLabel();
        PlayPause = new javax.swing.JLabel();
        Skip = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        CMusicName = new javax.swing.JLabel();
        BackToHome1 = new javax.swing.JLabel();
        PodcastArtist = new javax.swing.JLabel();
        PodcastTitle = new javax.swing.JLabel();
        PlayerStatus = new javax.swing.JLabel();
        Shuffle = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mp3Art.setBackground(new java.awt.Color(255, 255, 255));
        Mp3Art.setForeground(new java.awt.Color(255, 255, 255));
        Mp3Art.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/NoMusicArt.png"))); // NOI18N
        Mp3Art.setPreferredSize(new java.awt.Dimension(300, 300));
        getContentPane().add(Mp3Art, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 350, 350));

        PlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Play 03.png"))); // NOI18N
        PlayPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayPauseMouseClicked(evt);
            }
        });
        getContentPane().add(PlayPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, -1, 90));

        Skip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Skip Forward.png"))); // NOI18N
        Skip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SkipMouseClicked(evt);
            }
        });
        getContentPane().add(Skip, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 650, -1, -1));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Skip Back.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 650, -1, -1));

        jProgressBar1.setBackground(new java.awt.Color(218, 218, 218));
        jProgressBar1.setForeground(new java.awt.Color(255, 51, 0));
        jProgressBar1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBar1StateChanged(evt);
            }
        });
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, 540, 10));

        CMusicName.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        CMusicName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(CMusicName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        BackToHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Back.png"))); // NOI18N
        getContentPane().add(BackToHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PodcastArtist.setFont(new java.awt.Font("Prompt", 0, 14)); // NOI18N
        PodcastArtist.setForeground(new java.awt.Color(204, 204, 204));
        PodcastArtist.setText("--------------------------------------------------------------------------------------");
        PodcastArtist.setFocusable(false);
        PodcastArtist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(PodcastArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 520, 30));

        PodcastTitle.setFont(new java.awt.Font("Prompt", 0, 24)); // NOI18N
        PodcastTitle.setForeground(new java.awt.Color(255, 255, 255));
        PodcastTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PodcastTitle.setText("---------------------------------------------------");
        getContentPane().add(PodcastTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 520, 50));

        PlayerStatus.setFont(new java.awt.Font("Prompt", 0, 20)); // NOI18N
        PlayerStatus.setForeground(new java.awt.Color(255, 255, 255));
        PlayerStatus.setText("ไม่มีพอดแคสต์ที่กำลังเล่นอยู่");
        PlayerStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(PlayerStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        Shuffle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/ShuffleOff.png"))); // NOI18N
        Shuffle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShuffleMouseClicked(evt);
            }
        });
        getContentPane().add(Shuffle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 40, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/gradient.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1280, 832));
        background.setMinimumSize(new java.awt.Dimension(1280, 832));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayPauseMouseClicked
        if (isPlaying) {
            player.pause();
            PlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Play 03.png")));
        } else {
            player.resumeOrStart();
            PlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Pause 03.png")));
        }
        isPlaying = !isPlaying;
        updatePodcastInfo();
        updatePodcastArt();
    }//GEN-LAST:event_PlayPauseMouseClicked

    private void SkipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SkipMouseClicked
        player.next();
        updatePodcastInfo();
        updatePodcastArt();
    }//GEN-LAST:event_SkipMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        player.previous();
        updatePodcastInfo();
        updatePodcastArt();
    }//GEN-LAST:event_BackMouseClicked

    private void jProgressBar1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBar1StateChanged

    }//GEN-LAST:event_jProgressBar1StateChanged

    private void ShuffleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShuffleMouseClicked
        if (isShuffle) {
            player.loadMp3Files(); // โหลดไฟล์ MP3 ใหม่ตามลำดับเดิม
            Shuffle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/ShuffleOff.png")));
            System.out.println("Shuffle disabled. Back to original order.");
        } else {
            // เปิด Shuffle: สุ่มลำดับเพลง
            player.shuffle();
            Shuffle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/ShuffleOn.png")));
            System.out.println("Shuffle enabled.");
        }

        isShuffle = !isShuffle; // สลับสถานะ Shuffle
        updatePodcastInfo();
        updatePodcastArt();
    }//GEN-LAST:event_ShuffleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PodcastMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PodcastMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PodcastMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PodcastMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PodcastMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel BackToHome1;
    private javax.swing.JLabel CMusicName;
    private javax.swing.JLabel Mp3Art;
    private javax.swing.JLabel PlayPause;
    private javax.swing.JLabel PlayerStatus;
    private javax.swing.JLabel PodcastArtist;
    private javax.swing.JLabel PodcastTitle;
    private javax.swing.JLabel Shuffle;
    private javax.swing.JLabel Skip;
    private javax.swing.JLabel background;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
