/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

/**
 *
 * @author zaqwe
 */
public class Upload extends javax.swing.JFrame {
        private MediaControl player;
        private String userHome = System.getProperty("user.home");
        private String musicFolderPath = userHome + "\\Documents\\NetBeansProjects\\JavaApplication1\\music";
        
    public Upload() {
        initComponents();
        player = new MediaControl(musicFolderPath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JLabel();
        uploadPodcastBtn = new javax.swing.JLabel();
        uploadMusicBtn = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 832));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("อัพโหลดไฟล์เพลงหรือพอดแคสต์ของคุณ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("**รับรองไฟล์ MP3 เท่านั้น**");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/Back.png"))); // NOI18N
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        uploadPodcastBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uploadPodcastBtn.png"))); // NOI18N
        uploadPodcastBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadPodcastBtnMouseClicked(evt);
            }
        });
        getContentPane().add(uploadPodcastBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, -1, -1));

        uploadMusicBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/uploadMusicBtn.png"))); // NOI18N
        uploadMusicBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadMusicBtnMouseClicked(evt);
            }
        });
        getContentPane().add(uploadMusicBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/gradient.png"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(1280, 832));
        Background.setMinimumSize(new java.awt.Dimension(1280, 832));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadMusicBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadMusicBtnMouseClicked
    this.dispose();
    
    // เปิดหน้าจอ PodcastUpload
    PodcastUpload podcastUpload = new PodcastUpload();
    podcastUpload.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
    podcastUpload.setVisible(true);
    }//GEN-LAST:event_uploadMusicBtnMouseClicked

    private void uploadPodcastBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadPodcastBtnMouseClicked
        this.dispose();
    
        // เปิดหน้าจอ MusicUpload
        MusicUpload musicUpload = new MusicUpload();
        musicUpload.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
        musicUpload.setVisible(true);
    }//GEN-LAST:event_uploadPodcastBtnMouseClicked

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        this.dispose();
    
        // เปิดหน้าจอ MainMenu
        MainMenu mainMenu = new MainMenu();
        mainMenu.setLocationRelativeTo(null); // ตั้งให้อยู่ตรงกลางหน้าจอ
        mainMenu.setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Upload().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel uploadMusicBtn;
    private javax.swing.JLabel uploadPodcastBtn;
    // End of variables declaration//GEN-END:variables
}
